- Demo/PowerSyncExample/PowerSync/SupabaseConnector.swift
- README.md
* Improve demo `uploadData` function to handle fatal postgres errors.
* Fix link error in docs
I added RLS to `lists` table in Supabase and then added new a list. Initially the error was not handled after the change the error is now handled and the queue is not blocked.
> chore: improve demo upload data to handle fatal errors

- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
Update `powersync-sqlite-core` package
> chore: update powersync-sqlite-core

- CHANGELOG.md
- Demo/README.md
Improve README based on this feedback https://coda.io/d/_dJ2KYEAhP7V/Setup-and-Demo-Notes_su21ftw8#_luQBCzqy and update CHANGELOG based on recent release
> docs: improve readme add to changelog

- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Demo/PowerSyncExample/PowerSync/SystemManager.swift
- Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/Kotlin/KotlinTypes.swift
- Sources/PowerSync/Kotlin/SqlCursor.swift
- Sources/PowerSync/QueriesProtocol.swift
- Tests/PowerSyncTests/Kotlin/KotlinPowerSyncDatabaseImplTests.swift
- Tests/PowerSyncTests/Kotlin/SqlCursorTests.swift
* Allow cursor to use column name to get value by including the following functions that accept a column name parameter:
`getBoolean`,`getBooleanOptional`,`getString`,`getStringOptional`, `getLong`,`getLongOptional`, `getDouble`,`getDoubleOptional`
* Adapted demos
* Updated `powersync-kotlin` package to latest version
Note: The SqlCursor interface to user has not changed
Added unit tests for `SqlCursor` changes and ran the demo
> feat: add SqlCursor function improvements

- docs/LocalBuild.md
- docs/Release.md
Add a release guide and local development guide for internal users.
> docs: add release guide

- Demo/PowerSyncExample/PowerSync/SupabaseConnector.swift
- Sources/PowerSync/PowerSyncCredentials.swift
Add a default value of `nil` for `userId` in `PowerSyncCredentials` so users do not always need to include a `nil` value in their `fetchCredentials` function. I removed the `userId` from the example app as this is not useful for people trying to use the demo and could end up being a red herring.
Ran the demo app
> chore: add default to userId in PowerSyncCredentials

- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Demo/PowerSyncExample/Components/TodoListView.swift
- Demo/PowerSyncExample/PowerSync/SystemManager.swift
- Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/QueriesProtocol.swift
- Tests/PowerSyncTests/Kotlin/KotlinPowerSyncDatabaseImplTests.swift
Allow `execute`, `watch` and `transaction` functions to throw in Swift allowing users to handle them. This makes breaking changes to `watch` and `transaction` functions as they now require a `try` before implementation.
Includes changelog updates as well in preparation for the `Beta.6` release.
Tests have been included to confirm errors are thrown and can be handled and show an error log of the issue. I also ran the demo app to confirm it works as expected.
> chore: make execute, watch and transaction functions throwable in swift

- Demo/PowerSyncExample/Components/ListView.swift
- Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/PowerSyncDatabaseProtocol.swift
Support bucket priorities through the Kotlin SDK. The only Swift change is that we're exposing the new `waitForFirstSync(priority)` API.
> Support bucket priorities

- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Demo/PowerSyncExample/PowerSync/SystemManager.swift
- Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/QueriesProtocol.swift
- Tests/PowerSyncTests/Kotlin/KotlinPowerSyncDatabaseImplTests.swift
This applies the latest watched query updates from https://github.com/powersync-ja/powersync-kotlin/pull/136.
The current Query protocol is a bit verbose due to handling optional function parameters. Watched queries now support an optional `throttleMs` parameter. Adding this new param to the current structure would require a function definition for every possible permutation of optional arguments. A new struct based approach has been added for the `watch` method, this handles optional arguments better.
> Watched Query Fixes

- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/PowerSyncDatabaseProtocol.swift
- Tests/PowerSyncTests/Kotlin/KotlinPowerSyncDatabaseImplTests.swift
This updates the Kotlin package dependency to 1.0.0-BETA28.  Relevant changes include:
* Update PowerSync SQLite core extension to 0.3.12.
* Added queuing protection and warnings when connecting multiple PowerSync clients to the same database file.
* Improved concurrent SQLite connection support. A single write connection and multiple read connections are used for concurrent read queries.
* Internally improved the linking of SQLite.
* Enabled Full Text Search support.
* Added the ability to update the schema for existing PowerSync clients.
* Fixed bug where local only, insert only and view name overrides were not applied for schema tables.
> Upstream Updates

- .github/workflows/build_and_test.yaml
- CHANGELOG.md
- Package.resolved
- Package.swift
- Sources/PowerSync/PowerSyncBackendConnectorAdapter.swift
This updates `powersync-kotlin` to version `1.0.0-BETA29` and enables testing on macOS.
> Update powersync-kotlin version

- .github/workflows/docs.yaml
- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Demo/PowerSyncExample/Components/ListView.swift
- Sources/PowerSync/Kotlin/sync/KotlinSyncStatusData.swift
- Sources/PowerSync/Protocol/sync/DownloadProgress.swift
- Sources/PowerSync/Protocol/sync/SyncStatusData.swift
This ports the sync progress APIs over from Kotlin (using an identical API mirrored with Swift protocols). It also adds an example to the demo app which now shows a progress bar for the first sync.
> Add sync progress APIs

- CHANGELOG.md
- Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinAdapter.swift
- Sources/PowerSync/Kotlin/db/KotlinCrudEntry.swift
- Sources/PowerSync/Protocol/Schema/Table.swift
- Sources/PowerSync/Protocol/db/CrudEntry.swift
- Tests/PowerSyncTests/CrudTests.swift
- Tests/PowerSyncTests/Schema/TableTests.swift
- docs/LocalBuild.md
This prepares to update the Kotlin SDK (but we'll need to release the pending draft release first, which is the first one attaching the XCFramework). I've also changed the build logic to allow setting a local Kotlin build as a source in one place.
Additionally, this ports the new table options over with the same interface used on our other SDKs.
This depends on the draft release created by https://github.com/powersync-ja/powersync-kotlin/pull/190 to be released.
> Prepare Kotlin update, add schema options

- CHANGELOG.md
- Sources/PowerSync/Protocol/db/CrudBatch.swift
- Sources/PowerSync/Protocol/db/CrudTransaction.swift
- Tests/PowerSyncTests/CrudTests.swift
The current `CrudBatch` protocol does not provide a default value for the `complete` method's optional `writeCheckpoint` parameter. This PR adds a Protocol extension which provides the default value.
> Default Param for CrudBatch Complete

- CHANGELOG.md
- Package.swift
This updates the Kotlin xcframework to version 1.1.1. I've also copied relevant changelog entries.
> Update Kotlin SDK version to 1.1.1

- CHANGELOG.md
- Package.resolved
- Package.swift
This updates the version of the core extension to 0.4.1 ([release notes](https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.4.1)). The main benefit is that we properly reset statements with the new sync client with this update.
> Update core extension to 0.4.1

- .github/workflows/build_and_test.yaml
- Package.swift
This adds watchOS support to the Swift SDK, as well as the ability to test the SDK with a local build of the core extension.
> watchOS support

- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
This updates the PowerSync Kotlin SDK to the most recent version (1.2.2) and updates the changelog to prepare a release for the Swift SDK.
> Update Kotlin, prepare release

- Package.resolved
- Package.swift
This updates the core extension to 0.4.2. For release notes, see: https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.4.2
> Update core extension to 0.4.2

- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
- Sources/PowerSync/Kotlin/KotlinAdapter.swift
- Sources/PowerSync/Protocol/Schema/RawTable.swift
- Sources/PowerSync/Protocol/Schema/Schema.swift
- Sources/PowerSync/Protocol/Schema/Table.swift
This updates the Kotlin SDK to the recently released 1.3.0 and prepares a Swift release. It also adds a struct for raw tables and translates them to the Kotlin schema (unfortunately, this is hard to test since testing this realistically requires a mocked sync service. I've tested this manually in the demo app).
> Update Kotlin SDK, support raw tables

- CHANGELOG.md
- Package.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/Protocol/PowerSyncDatabaseProtocol.swift
This updates the Kotlin SDK framework to 1.3.1, removes the option to connect with websockets and prepares a release of the Swift SDK.
> Update Kotlin SDK to 1.3.1

- CHANGELOG.md
- Demo/PowerSyncExample/PowerSync/SystemManager.swift
- Package.swift
- Sources/PowerSync/Kotlin/KotlinNetworkLogger.swift
- Sources/PowerSync/Kotlin/KotlinPowerSyncDatabaseImpl.swift
- Sources/PowerSync/Protocol/NetworkLogger.swift
- Sources/PowerSync/Protocol/PowerSyncDatabaseProtocol.swift
- Sources/PowerSync/Protocol/SyncRequestLogger.swift
- Tests/PowerSyncTests/ConnectTests.swift
This adds the ability to log PowerSync network requests. This is the Swift port of https://github.com/powersync-ja/powersync-kotlin/pull/229.
This also removes the experimental `ConnectionMethod` options which have recently been removed from the Kotlin SDK.
> Add network logging support

- CHANGELOG.md
- Package.resolved
- Package.swift
This updates the core extension to version 0.4.4 and prepares a release of the Swift SDK.
> Update core extension, prepare release

- .github/workflows/build_and_test.yaml
- CHANGELOG.md
- Sources/PowerSync/Kotlin/DatabaseLogger.swift
This internally updates the Kotlin Kermit logger instantiation to be performed directly in the Swift Adapter. We previously relied on the `generateLogger` method of the Kotlin SDK. This method might be updated or removed in future - e.g. as in https://github.com/powersync-ja/powersync-kotlin/pull/242
> [Internal] Logger Updates

- .github/workflows/build_and_test.yaml
- CHANGELOG.md
- Demo/PowerSyncExample.xcodeproj/project.pbxproj
- Demo/PowerSyncExample/Screens/HomeScreen.swift
- Demo/PowerSyncExample/Screens/SignInScreen.swift
- Demo/PowerSyncExample/Screens/SignUpScreen.swift
- Package.swift
- README.md
This applies the workaround mentioned in https://github.com/powersync-ja/powersync-swift/issues/9 for restoring XCode previews.
Currently users are required to enable `Use Legacy Previews Execution` in order to use XCode's screen preview functionality. The previews fail to load with an error "Failed to launch app [App name] in reasonable time". The diagnostics report provided does not seem to provide any meaningful information to assist with debugging.
**PowerSync SPM Package Context**
The PowerSync SPM package currently includes a `PowerSync` `library` `product` which uses the default value for the `type` setting. According to the SPM docs for the `type` setting:
```
Creates a library product to allow clients that declare a dependency on this package to use the package's functionality.
A …
```
> XCode Previews

- CHANGELOG.md
- Package.swift
Release for:
* Update core extension to 0.4.5 ([changelog](https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.4.5))
* Additional Swift 6 Strict Concurrency Checking declarations added for remaining protocols in https://github.com/powersync-ja/powersync-swift/pull/75
* Fix issue in legacy sync client where local writes made offline could have their upload delayed until a keepalive event was received. This could also cause downloaded updates to be delayed even further until all uploads were completed in https://github.com/powersync-ja/powersync-kotlin/pull/255
> [Release] 1.5.1
